atom-community/ide-python

.travis.yml, lib/main.js, package.json
=> Add ability to configure plugins

package.json
atom-languageclient@0.6.5 added support for adapting signature help. Try it out and let me know what you think! :)
https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/signature-help.md
Contributed under CC0.
=> Add signature help support

lib/main.js
Made extension virtualenv aware by exporting VIRTUAL_ENV when bin/python detected from project root, fixing #37
=> Made extension virtualenv aware

lib/main.js
See
https://github.com/atom/ide-typescript/commit/d9d259214c7b73d062878b60d68e2c1bc168c721
=> Force server shutdown after 2 seconds

package.json
Enabled Jedi Symbols: All Scopes setting by default
=> Enabled Jedi Symbols, All Scopes

lib/main.js, lib/utils.js, spec/utils-spec.js
=> Implement virtualenv detection for Windows

lib/main.js, package.json
=> accept flake8 as a config source, rather than pyflakes

README.md, lib/main.js, package.json
Closes #9 
Closes #42
Closes #78
=> Support pycodestyle ignore and select option

package.json
=> fix(package): update atom-languageclient to version 0.9.1

README.md, lib/main.js, package.json
`pyls` 0.17 is out 🎉: https://github.com/palantir/python-language-server/releases/tag/0.17.0
Closes #96
=> Add full support for pyls 0.17

package.json
Forgot to update the documentation in e521120a8476c8aef10e30cfc4b15db06ef47050
=> Fix rope folder documentation

package.json
See: https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/code-highlight.md
=> Support document hightlights introduced in pyls 0.19

package.json
Upgrade and pin [`atom-languageclient@0.9.9`](https://github.com/atom/atom-languageclient/blob/master/CHANGELOG.md)
=> Bump atom-languageclient@0.9.9

package.json
Depends on https://github.com/palantir/python-language-server/pull/457
=> Add `follow_imports` config to goto-definition

lib/main.js, lib/utils.js, spec/utils-spec.js
=> chore: Run prettier

package.json
See https://github.com/palantir/python-language-server/issues/512
=> Add jedi completion include params option

package.json
This PR adds support  for Pylint. This will be disabled by default to not change the existing behavior.
=> Add support for Pylint plugin

package.json
Reverts atom-ide-community/ide-python#213 to fix #216
=> Revert "Update dependency atom-languageclient to v1"

package.json
atom-languageclient v1.0.6 should fix the completion errors
=> fix(deps): update atom-languageclient to ^1.0.6

.eslintrc.json, .github/workflows/CI.yml, babel.config.js, lib/debugger/RemoteDebuggerCommandService.js, lib/debugger/utils.js, lib/main.js, lib/utils.js, package.json, pnpm-lock.yaml
=> fix: default to python3 and fallback to python

lib/main.js, package.json
=> fix: config works with pylsp / pyls

lib/main.js
=> fix: configs not working for the deprecated pyls

lib/main.js
=> fix: fix replacing $PIPENV_PATH in the python path
